
#include "eksamen_v23_oppgave2_fib.c"
#include "eksamen_v23_oppgave2_prim.c"
#include "eksamen_v23_oppgave2_kvad.c"
#include "eksamen_v23_oppgave2_cube.c"
#include "eksamen_v23_oppgave2_perf.c"
#include "eksamen_v23_oppgave2_abun.c"
#include "eksamen_v23_oppgave2_def.c"
#include "eksamen_v23_oppgave2_odd.c"
#include "task_2.c"
